Modshell ver.>2.0
Title of Site>Sagebrush canopy with residue
Start day(julian)>337
Start year>86
Start hour>24
End day(julian)>350
End year>86
Weather file>trial.wea
Hours per Time Step>24
Time step for weather date>0
Latitude(deg)>46
Latitude(min)>45
Slope(degrees)>15.000
Aspect(degrees)>180.000
Elevation>6500.000
Snow depth(cm)>0.000
Snow Temperature(øC)>0.000
Snow Equivilent>0.000
Residue depth(cm)>2.000
Residue biomass>6000.000
Residue Cover>90.000
Residue Albedo>0.300
Surface roughness>0.600
Depth of ponding>0.000
Plant types>1
Standing dead(0/1)>0
  Plant0 height>0.900
  Plant0 leaf area index>2.500
  Plant0 biomass>1.500
  Plant0 albedo>0.250
  Plant0 leaf angle>1
  Plant0 transpiration temperature>7.000
  Plant0 min. stomatal resistance>100.000
  Plant0 stomatal resistance exp.>5.000
  Plant0 leaf water potential>-30.000
  Plant0 plant resistance>2400000.000
  Plant0 leaf dimensions>0.500
  Plant0 rooting depth>1.00
Soil Albedo dry>0.150
Soil Albedo wet>0.150
Soil Depth to water table>0.000
Soil Air Temperature>8.000
Soil layers>11
  Soil layer0 depth>0.000
  Soil layer0 init temp>1.100
  Soil layer0 init moisture>0.370
  Soil layer0 percent clay>30.000
  Soil layer0 percent sand>10.000
  Soil layer0 percent silt>60.000
  Soil layer0 percent organic matter>0.000
  Soil layer0 bulk density>1.020
  Soil layer0 sat. moisture content>0.513
  Soil layer0 sat. conductivity>0.589
  Soil layer0 air-entry potential>0.040
  Soil layer0 pore-size distribution>5.243
  Soil layer1 depth>5.000
  Soil layer1 init temp>1.900
  Soil layer1 init moisture>0.370
  Soil layer1 percent clay>30.000
  Soil layer1 percent sand>10.000
  Soil layer1 percent silt>60.000
  Soil layer1 percent organic matter>0.000
  Soil layer1 bulk density>1.020
  Soil layer1 sat. moisture content>0.513
  Soil layer1 sat. conductivity>0.589
  Soil layer1 air-entry potential>0.040
  Soil layer1 pore-size distribution>5.243
  Soil layer2 depth>10.000
  Soil layer2 init temp>2.800
  Soil layer2 init moisture>0.370
  Soil layer2 percent clay>30.000
  Soil layer2 percent sand>10.000
  Soil layer2 percent silt>60.000
  Soil layer2 percent organic matter>0.000
  Soil layer2 bulk density>1.020
  Soil layer2 sat. moisture content>0.513
  Soil layer2 sat. conductivity>0.589
  Soil layer2 air-entry potential>0.040
  Soil layer2 pore-size distribution>5.243
  Soil layer3 depth>15.000
  Soil layer3 init temp>3.700
  Soil layer3 init moisture>0.380
  Soil layer3 percent clay>30.000
  Soil layer3 percent sand>10.000
  Soil layer3 percent silt>60.000
  Soil layer3 percent organic matter>0.000
  Soil layer3 bulk density>1.100
  Soil layer3 sat. moisture content>0.513
  Soil layer3 sat. conductivity>0.589
  Soil layer3 air-entry potential>0.040
  Soil layer3 pore-size distribution>5.243
  Soil layer4 depth>20.000
  Soil layer4 init temp>4.400
  Soil layer4 init moisture>0.270
  Soil layer4 percent clay>30.000
  Soil layer4 percent sand>10.000
  Soil layer4 percent silt>60.000
  Soil layer4 percent organic matter>0.000
  Soil layer4 bulk density>1.100
  Soil layer4 sat. moisture content>0.513
  Soil layer4 sat. conductivity>0.589
  Soil layer4 air-entry potential>0.040
  Soil layer4 pore-size distribution>5.243
  Soil layer5 depth>30.000
  Soil layer5 init temp>5.400
  Soil layer5 init moisture>0.290
  Soil layer5 percent clay>30.000
  Soil layer5 percent sand>10.000
  Soil layer5 percent silt>60.000
  Soil layer5 percent organic matter>0.000
  Soil layer5 bulk density>1.100
  Soil layer5 sat. moisture content>0.513
  Soil layer5 sat. conductivity>0.589
  Soil layer5 air-entry potential>0.040
  Soil layer5 pore-size distribution>5.243
  Soil layer6 depth>50.000
  Soil layer6 init temp>6.200
  Soil layer6 init moisture>0.300
  Soil layer6 percent clay>30.000
  Soil layer6 percent sand>10.000
  Soil layer6 percent silt>60.000
  Soil layer6 percent organic matter>0.000
  Soil layer6 bulk density>1.100
  Soil layer6 sat. moisture content>0.513
  Soil layer6 sat. conductivity>0.589
  Soil layer6 air-entry potential>0.040
  Soil layer6 pore-size distribution>5.243
  Soil layer7 depth>70.000
  Soil layer7 init temp>6.700
  Soil layer7 init moisture>0.300
  Soil layer7 percent clay>30.000
  Soil layer7 percent sand>10.000
  Soil layer7 percent silt>60.000
  Soil layer7 percent organic matter>0.000
  Soil layer7 bulk density>1.090
  Soil layer7 sat. moisture content>0.513
  Soil layer7 sat. conductivity>0.589
  Soil layer7 air-entry potential>0.040
  Soil layer7 pore-size distribution>5.243
  Soil layer8 depth>100.000
  Soil layer8 init temp>7.500
  Soil layer8 init moisture>0.340
  Soil layer8 percent clay>30.000
  Soil layer8 percent sand>10.000
  Soil layer8 percent silt>60.000
  Soil layer8 percent organic matter>0.000
  Soil layer8 bulk density>1.090
  Soil layer8 sat. moisture content>0.513
  Soil layer8 sat. conductivity>0.589
  Soil layer8 air-entry potential>0.040
  Soil layer8 pore-size distribution>5.243
  Soil layer9 depth>120.000
  Soil layer9 init temp>8.400
  Soil layer9 init moisture>0.330
  Soil layer9 percent clay>30.000
  Soil layer9 percent sand>10.000
  Soil layer9 percent silt>60.000
  Soil layer9 percent organic matter>0.000
  Soil layer9 bulk density>1.290
  Soil layer9 sat. moisture content>0.513
  Soil layer9 sat. conductivity>0.589
  Soil layer9 air-entry potential>0.040
  Soil layer9 pore-size distribution>5.243
  Soil layer10 depth>150.000
  Soil layer10 init temp>9.400
  Soil layer10 init moisture>0.340
  Soil layer10 percent clay>30.000
  Soil layer10 percent sand>10.000
  Soil layer10 percent silt>60.000
  Soil layer10 percent organic matter>0.000
  Soil layer10 bulk density>1.280
  Soil layer10 sat. moisture content>0.513
  Soil layer10 sat. conductivity>0.589
  Soil layer10 air-entry potential>0.040
  Soil layer10 pore-size distribution>5.243
Water flow boundary condition>1
Output files path>c:\shaw23
Output files extension>msh
Output interval index> 24  0  1 24  0 24 24  0  0  0  0  0  0
Heat flow boundary condition>0
Initial and Boundary temperature file>shaw.tmp
Initial and Boundary water content file>shaw.moi
path for shaw input files>D:\SHAW23\DISK
file name for modshell>TRIALMOD
